### PR TITLE
Use pushd/popd for reliable directory changing

### PR DESCRIPTION
**Pull request by 501st-alpha1**
Small change that I saw could be made. I'll be trying to get this set up on my server, so I might send another PR later to automate the first-time setup.

### CODE REVIEW

**Comment by wolfgang42** [comment]
The second `cd` (without any arguments) is actually completely unused--it comes from my habit of leaving a directory before I delete it, so I don't wind up with my working directory being a deleted folder. The script will still work fine without it.

First-time setup is easy: just run the `aptly repo create` comand at the top of update.sh. However, this script wasn't meant to be installed by someone else, so you'll find paths to /var/www hardcoded, as well as my GPG key.

**Comment by 501st-alpha1** [comment]
Ah okay, that makes sense. I'll close this PR then.

Yeah I had noticed the hard-coded stuff, and I was going to try to see if I could find a way to make it easily customizable (mostly because I like to automate things, haha). Would you be open to such a PR if I can get it working?

**Comment by wolfgang42** [comment]
Sure, I'll take a pull request, though I don't foresee a need for a proliferation of Vagrant deb repositories.

Actually, I think the only things that are hardcoded are the GPG key in update.sh and rootDir in aptly.conf. Everything else uses $BASEDIR.

**Comment by 501st-alpha1** [comment]
Yeah, now that I've looked at it a little more, I think it's fine as-is. I managed to get it working, thanks!

**Pull request closed without merging**
