### PR TITLE
Update apt-key command to be less error prone

### PR DESCRIPTION
**Pull request by carstendietrich**
Hello,

commit adds protocol and port to the command. Without these I could not get the keyserver to work correctly (Ubuntu 16.04 LTS):

```
$ sudo apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
gpg: requesting key 2099F7A4 from hkp server pgp.mit.edu

gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

```
$ sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
gpg: requesting key 2099F7A4 from hkp server pgp.mit.edu
gpg: key 2099F7A4: public key "vagrant-deb.linestarve.com automatic signing key <wolfgangmcq+vagrant-deb@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

```

Kind regards

### CODE REVIEW

**Comment by wolfgang42** [comment]
Were you seeing a similar error message to the one described in #9? I don't think that specifying protocol and port should make a difference, but several users have reported intermittent errors with the MIT keyserver. I use this repo myself on several different 16.04 machines and I've never needed to specify anything other than the domain name for the keyserver.

**Comment by carstendietrich** [comment]
The error specified in issue #9 didn't occur. The change aims for people behind a firewall or in a restricted company network. Sometimes the key server ports are blocked so switching to a more common port can solve these problems. There for the command is less error prone.

**Comment by wolfgang42** [comment]
Thanks for the clarification. I've updated the keyserver address in the meantime, so if you want to rebase and submit an updated commit I will merge this soon.

**Comment by carstendietrich** [comment]
Hello,
rebase didn't work, had to merge.

**Comment by wolfgang42** [comment]
Thanks! I've merged this in and updated the server.

**Pull request merged**
